repos:
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        language: system
        entry: pytest
        pass_filenames: false
        always_run: true
        stages: [commit, manual]

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.6.2
    hooks:
      - id: pyupgrade
        stages: [manual]
        args:
          - "--py37-plus"

  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
        stages: [commit, manual]
        args:
          - --safe
          - --quiet
        files: ^((custom_components|script|tests)/.+)?[^/]+\.py$

  - repo: https://github.com/codespell-project/codespell
    rev: v1.17.1
    hooks:
      - id: codespell
        stages: [commit, manual]
        args:
          - --quiet-level=2
          - --ignore-words-list=hass,ba,fo,mabe

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: check-json
        stages: [commit, manual]
      - id: requirements-txt-fixer
        stages: [commit, manual]
      - id: check-ast
        stages: [commit, manual]
      - id: mixed-line-ending
        stages: [commit, manual]
        args:
          - --fix=lf
